SmartFarm/SmartFarm/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SmartFarm.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Vui lòng điền tên đăng nhập")]
        [StringLength(16, MinimumLength = 8, ErrorMessage = "Tên đăng nhập phải từ 8-16 kí tự")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Vui lòng điền mật khẩu")]
        [StringLength(16, MinimumLength = 8, ErrorMessage = "Mật khẩu phải từ 8-16 kí tự")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[#$^+=!*()@~%&]).{8,}$", ErrorMessage = "Mật khẩu phải có ít nhất một ký tự in hoa, số và ký tự đặc biệt")]
        public string Password { get; set; }
        public string ErrorMessage { get; set; }
    }
}

SmartFarm/SmartFarm/Controllers/InputDeviceController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SmartFarm.Models;
using SmartFarm.Services;

namespace SmartFarm.Controllers
{
    public class InputDeviceController : Controller
    {
        private readonly IInputService _inputService;
        public InputDeviceController(IInputService inputService)
        {
            _inputService = inputService;
        }
        [HttpGet]
        public async Task<IActionResult> SetUpNguong()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Home");
            }
            var input=await _inputService.GetInputsAsync();
            return View(input);
        }
        [HttpPost]
        public IActionResult SetNguong(InputModel input)
        {
            input.timeSet=TimeSpan.FromSeconds(input.secondTime);
            _inputService.UpdateSetNguong(input);
            return RedirectToAction("SetUpNguong");
        }

    }
}

SmartFarm/SmartFarm/Controllers/OutputDeviceController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SmartFarm.Services;

namespace SmartFarm.Controllers
{
    public class OutputDeviceController : Controller
    {
        private readonly IOutputService _output;
        public OutputDeviceController(IOutputService output){
            _output = output;
        }
        [HttpGet]
        public async Task<IActionResult> ControlDevice()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Home");
            }
            var outputs= await _output.GetOutputAsync();
            return View(outputs);
        }
        [HttpPost]

        public IActionResult UpdateAutoController(int i,int id)
        {
            _output.SetAutOutput(i,id);
           return RedirectToAction("ControlDevice"); 
        }
    }
}

SmartFarm/SmartFarm/Controllers/StatisticController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SmartFarm.Models;
using SmartFarm.Services;

namespace SmartFarm.Controllers
{
    public class StatisticController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IInputService _inputService;

        public StatisticController(ILogger<HomeController> logger,IInputService inputService)
        {
            _logger = logger;
            _inputService = inputService;
        }
        public async Task<IActionResult> ThonkeAsync()
        {
            var input=await _inputService.GetInputsAsync();
            InputAndOutputModel result=new InputAndOutputModel();
            result.Inputs=input;
            return View(result);
        }
        [HttpGet]
        public async Task<IActionResult> InputAsync(int id)
        {
            var input=await _inputService.GetInputIdAsync(id);

            return View(input);
        }


        public IActionResult Output()
        {
            return View();
        }
    }
}

SmartFarm/SmartFarm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmartFarm</title>
    <link rel="stylesheet" type="text/css" href="/css/site.css" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />

 
    <!-- GOOGLE FONT -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@500;600;700&family=Lato:wght@300;400;700;900&family=Reggae+One&display=swap"
      rel="stylesheet"
    />
    @await RenderSectionAsync("CustomCss",false)
</head>
<body>
    <header>
        <nav
      class="navbar navbar-expand-md navbar-light bg-light nav-bar p-0 pl-md-5 fixed-top"
    >
      <!-- <div class="container-fluid"> -->
      <div class="nav-logo">
        <a href="@Url.Action("Home","Home")" class="navbar-brand p-4 py-md-0 d-inline-block">AEFARM</a>
      </div>

      <button
        class="navbar-toggler me-4"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="dropdown align-self-stretch d-block d-md-none">
          <div
            class="dropdown-toggle nav-user"
            id="dropdownMenuButton"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <span class="nav-user__avatar">
              <img src="/image/avatar.jpg" alt="User avatar" />
            </span>
            <span class="nav-user__name">Vu Tran</span>
          </div>

          <div
            class="dropdown-menu nav-user__dropdown"
            aria-labelledby="dropdownMenuButton"
          >
            <a class="dropdown-item nav-user__dropdown-item" href="@Url.Action("InforUser","Home")"
              >Thông tin cá nhân</a
            >
            <a class="dropdown-item nav-user__dropdown-item" href="@Url.Action("ManageDeivce","Home")"
              >Quản lý thiết bị</a
            >
            <a class="dropdown-item nav-user__dropdown-item" href="@Url.Action("Login","Home")"
              >Đăng xuất</a
            >
          </div>
        </div>
        <ul class="navbar-nav me-auto">
          <li class="nav-item nav__item">
            <a class="nav-link nav__link" aria-current="page" href="@Url.Action("Home","Home")"
              >Trang chủ</a
            >
          </li>

          <li class="nav-item nav__item">
            <a class="nav-link nav__link" href="@Url.Action("controlDevice","OutputDevice")">Điều khiển</a>
          </li>
          <li class="nav-item nav__item">
            <a class="nav-link nav__link" href="@Url.Action("setUpNguong","InputDevice")">Thiết lập ngưỡng</a>
          </li>
          <li class="nav-item nav__item">
            <a class="nav-link nav__link" href="@Url.Action("Thonke","Statistic")">Xem thống kê</a>
          </li>
        </ul>
        <div class="dropdown align-self-stretch d-none d-md-inline-block">
          <div
            class="dropdown-toggle nav-user"
            id="dropdownMenuButton"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <span class="nav-user__avatar">
              <img src="/image/avatar.jpg" alt="User avatar" />
            </span>
            <span class="nav-user__name">Vu Tran</span>
          </div>

          <div
            class="dropdown-menu nav-user__dropdown"
            aria-labelledby="dropdownMenuButton"
          >
            <a class="dropdown-item nav-user__dropdown-item" href="@Url.Action("InforUser","Home")"
              >Thông tin cá nhân</a
            >
            <a class="dropdown-item nav-user__dropdown-item" href="@Url.Action("ManageDevice","Home")"
              >Quản lý thiết bị</a
            >
            <a class="dropdown-item nav-user__dropdown-item" href="@Url.Action("Login","Home")"
              >Đăng xuất</a
            >
          </div>
        </div>
      </div>
      <!-- </div> -->
    </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="footer">
      <div class="nav-logo lg-font my-5 mx-auto text-center">
        <a href="@Url.Action("Home","Home")" class="d-inline-block lg-font">AEFARM</a>
      </div>
      <ul class="nav">
        <li class="nav__item">
          <a href="#" class="nav__link">Find your dream home</a>
        </li>
        <li class="nav__item">
          <a href="#" class="nav__link">Request proposal</a>
        </li>
        <li class="nav__item">
          <a href="#" class="nav__link">Download home planner</a>
        </li>
        <li class="nav__item">
          <a href="#" class="nav__link">Contact us</a>
        </li>
        <li class="nav__item">
          <a href="#" class="nav__link">Submit your property</a>
        </li>
        <li class="nav__item">
          <a href="#" class="nav__link">Come work with us!</a>
        </li>
      </ul>
      <p class="copyright">
        &copy; Copyright 2022 by AE mien trung team. Feel free to use this
        project for your own purposes. This does NOT apply if you plan to
        produce your own course or tutorials based on this project.
      </p>
    </footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
      defer
    ></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SmartFarm/SmartFarm/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmartFarm</title>
    <link rel="stylesheet" type="text/css" href="/css/site.css" />
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.css" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />

 
    <!-- GOOGLE FONT -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@500;600;700&family=Lato:wght@300;400;700;900&family=Reggae+One&display=swap"
      rel="stylesheet"
    />
    @await RenderSectionAsync("CustomCss",false)
</head>
<body>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
      defer
    ></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SmartFarm/SmartFarm/Views/Shared/_LoginPartiall.cshtml
@using Microsoft.AspNetCore.Identity
@using SmartFarm.Data.Entities;
@using SmartFarm.Data;
@inject SignInManager<Customer> SignInManager
@inject UserManager<Customer> UserManager
@inject AppDbContext context
@if (SignInManager.IsSignedIn(User))
{
    <div class="dropdown align-self-stretch d-none d-md-inline-block">
        <div class="dropdown-toggle nav-user"
             id="dropdownMenuButton"
             data-bs-toggle="dropdown"
             aria-expanded="false">
            <span class="nav-user__name">Xin chào @UserManager.GetUserAsync(User).Result.UserName</span>
        </div>

        <div class="dropdown-menu nav-user__dropdown"
             aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item nav-user__dropdown-item" href="@Url.Action("InforUser","Home",new { UserName=UserManager.GetUserAsync(User).Result.UserName})">Thông tin cá nhân</a>
            <a class="dropdown-item nav-user__dropdown-item" href="@Url.Action("ManageDevice","Home")">Quản lý thiết bị</a>
            <a class="dropdown-item nav-user__dropdown-item" href="@Url.Action("Logout", "Home")">Đăng xuất</a>
        </div>
    </div>
}
else
{
    <div class="d-none d-md-flex nav-empty align-self-stretch px-4 align-items-center">
        <svg class="nav-empty__avatar">
            <use xlink:href="/image/spirite.svg#icon-user-solid-circle"></use>
        </svg>
        <a href="@Url.Action("Login", "Home")" class="nav-empty__link">Đăng nhập</a>
    </div>
}